### ISSUE TITLE
clicking outside widget's window leaves artifacts on Hyprland

### ISSUE THREAD

**Issue by pmoieni** [Aylur/dotfiles#172]
As shown in the video below when trying to close widgets by clicking outside their window, some weird artifacts show up.
my laptop has an Nvidia GPU but I've set up Hyprland to use the Intel iGPU so not sure if it's a graphical issue.

https://github.com/Aylur/ags/assets/62774242/e16aeec9-4793-4739-bf62-1881b004ea9e

**Comment by Aylur** [comment]
they must be the eventbox that I use to pad these popup windows so click away works
what is your gtk3 theme?

**Comment by pmoieni** [comment]
It's rose-pine, but can-focus is set to false on even boxes so this shouldn't be the intended behaviour right?

**Comment by Aylur** [comment]
try
```ts
// widget/PopupWindow.ts
export const Padding =
  class_name: "padding"
```
```scss
/* style/extra.scss */
window.popup-window .padding {
  all: unset;
  * { all: unset; }
}
```
