### ISSUE TITLE
Bring back bar with gaps between blocks

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#228]
I mean, this: 
![image](https://github.com/Aylur/dotfiles/assets/28739146/a7fbbd43-6b40-406c-9066-86b39d7da178)

This should be available as a configuration.

I understand that it can be difficult to use with the new implementation where active apps are listed in the top bar.
But with it, on screens with low resolutions, it pushes the middle section off the center. Like this:

![image](https://github.com/Aylur/dotfiles/assets/28739146/ac49c7f2-8497-4781-ab75-6f5530847e8c)

So I propose that, the left side and right side should have expandable icons, like the right side in the first image here.
The left side will expand to show active apps, and the right side will expand to show tray icons.

This will create a clean display.

It could be said that I should tidy up my workflow habits, but I think 8 workspaces are useless if I can't open one program in each of them without cluttering my bar. My resolution is 1280x1024 (5:4, crazy, but horizontally, same as 720p).

**Comment by Aylur** [comment]
I haven't ported this option to the current ts version because I found myself never using them
you can edit the css of the bar and buttons in `bar.scss`
```scss
.bar {
    background-color: transparent;

    .panel-button {
        @include panel-button($flat: false);
        >* {
            background-color: $bg;
        }
    }
}
```
this is not exactly how it was done before, but you should get the idea, you can check the old version if you want to reimplement it
