### ISSUE TITLE
Reload config? 

### ISSUE THREAD

**Issue by RoccoRakete** [Aylur/dotfiles#54]
How do I reload the config? 

Am I missing something? if I change something, save the file and restart ags, nothing has changed..

**Comment by Aylur** [comment]
in what file and where exectly are you trying to set the format?

**Comment by RoccoRakete** [comment]
in modules/clock.js

**Comment by RoccoRakete** [comment]
ohh wait, in widgets, it's been working...  so can you explain for what modules are?

**Comment by Aylur** [comment]
as for the workspaces the same thing is happening
you need to edit it in `layouts/widgets/hyprland.js`

**Comment by RoccoRakete** [comment]
> as for the workspaces the same thing is happening you need to edit it in `layouts/widgets/hyprland.js`

yep a got that already! 
Thank you for your help. There is so much to configure and to explore. 
Awesome work! :)

**Comment by RoccoRakete** [comment]
One more question, how do I disbale things like the desktopclock or the dock?

**Comment by Aylur** [comment]
comment them out in `layouts/topbar.js` `layouts/bottombar.js` at the bottom of the file where its exported

**Comment by RoccoRakete** [comment]
Is there an easy way to change the fontsize of the bar? Or do I have to edit this in the corresponding css files?

**Comment by Aylur** [comment]
just the css file
in `bar.scss`
```css
.panel{
  font-size: 20px;
}
```

**Comment by RoccoRakete** [comment]
> just the css file in `bar.scss`
> 
> ```css
> .panel{
>   font-size: 20px;
> }
> ```

that doesn't work :(

**Comment by Aylur** [comment]
try editing the mixin
```scss
@mixin panel_button($flat: false, $reactive: true){
    // ...
    label {
        font-weight: bold;
        font-size: 30px;
    }
    // ...
}
```
